#!/bin/dash

IMAGE_NAME=mve-image
CONTAINER_PORT=5000
LOCAL_PORT=3000

SOURCE_FOLDER=/Users/sunny/Desktop/videos
VOLUME_FOLDER=/mnt/videos

docker run \
    -v $SOURCE_FOLDER:$VOLUME_FOLDER \
    -p $LOCAL_PORT:$CONTAINER_PORT \
    # -t will give you pretty colours in terminal
    $IMAGE_NAME
