#!/bin/dash

IMAGE_NAME=mve-image
CONTAINER_PORT=5000
LOCAL_PORT=3000

SOURCE_FOLDER=/Users/sunny/Desktop/videos
VOLUME_FOLDER=/mnt/videos

docker run \
    -p $LOCAL_PORT:$CONTAINER_PORT -t $IMAGE_NAME \
    -v $SOURCE_FOLDER:$VOLUME_FOLDER
